version: '3'

services:
  distance-api-nginx:
    container_name: distance-api-nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./distance-api:/var/www/app
      - ./distance-api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - distance-api-php
    networks:
      - distance

  distance-api-php:
    container_name: distance-api-php
    build:
      context: .
      dockerfile: distance-api/docker/php/Dockerfile
    volumes:
      - ./distance-api:/var/www/app
    networks:
      - distance

  distance-front-nginx:
    container_name: distance-front-nginx
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./distance-front:/var/www/app
      - ./distance-front/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - distance-front-php
    links:
      - distance-api-nginx
    networks:
      - distance

  distance-front-php:
    container_name: distance-front-php
    build:
      context: .
      dockerfile: distance-front/docker/php/Dockerfile
    volumes:
      - ./distance-front:/var/www/app
    networks:
      - distance
networks:
  distance:
    driver: "bridge"